In [5]:
conda install numpy



==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3




Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\anaconda3

  added / updated specs:
    - numpy


The following packages will be UPDATED:

  ca-certificates                     2023.08.22-haa95532_0 --> 2023.12.12-haa95532_0 
  certifi                         2023.7.22-py311haa95532_0 --> 2023.11.17-py311haa95532_0 
  openssl                                 3.0.10-h2bbff1b_2 --> 3.0.12-h2bbff1b_0 





Preparing transaction: ...working... done
Verifying transaction: ...working... failed
Solving environment: ...working... done

## Package Plan ##

  environment location: C:\ProgramData\anaconda3

  added / updated specs:
    - numpy


The following packages will be UPDATED:

  ca-certificates                     2023.08.22-haa95532_0 --> 2023.12.12-haa95532_0 
  certifi                         2023.7.22-py311haa95532_0 --> 2023.11.17-py311haa95532_0 
  openssl                                 3.0.10-h2bbff1b_2 --> 3.0.12-h2bbff1b_0 







==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0



EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\anaconda3




In [2]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 24.3.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=24.3.0




In [ ]:
conda install conda=24.3.0

In [1]:
import numpy as np

In [2]:
#numpy array

In [3]:
my_list = [10,20,30,40]

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [7]:
my_numpy_array = np.array(my_list)

In [8]:
my_numpy_array

array([10, 20, 30, 40])

In [10]:
my_numpy_array[0]

10

In [11]:
my_numpy_array.mean()

25.0

In [12]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [13]:
np.array(matrix_list)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [14]:
numpy_matrix_list = np.array(matrix_list)

In [15]:
numpy_matrix_list[0]

array([1, 0, 0])

In [18]:
numpy_matrix_list.shape

(4, 3)

In [19]:
#arange

In [20]:
range(0,10)

range(0, 10)

In [22]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [32]:
#linspace

In [35]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [36]:
#random

In [41]:
np.random.randint(1,10,3)

array([5, 6, 7])

In [42]:
#numpy arrays method

In [43]:
my_numpy_list = np.arange(0,20)

In [44]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [46]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [47]:
my_list = list(range(0,20))

In [48]:
my_list[4:9:2]

[4, 6, 8]

In [50]:
#my_list[4:9] = -10

In [51]:
my_numpy_list[4:9] = -10

In [52]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [53]:
other_list = np.arange(0,15)

In [54]:
slicing_list = other_list[4:10]

In [55]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [56]:
slicing_list[:] = 100

In [57]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [58]:
other_list

array([  0,   1,   2,   3, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14])

In [59]:
numpy_list_3 = np.arange(0,20)

In [60]:
numpy_list_3_copy = numpy_list_3.copy()

In [63]:
slicing_3 = numpy_list_3_copy[4:9]

In [64]:
slicing_3[:] = -100

In [65]:
slicing_3

array([-100, -100, -100, -100, -100])

In [66]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [67]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [69]:
# numpy operations with numpy arrays

In [70]:
new_array = np.random.randint(1,150,25)

In [71]:
new_array > 50

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True])

In [72]:
result_array = new_array > 50

In [73]:
result_array

array([False,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True, False, False,  True,
        True, False, False,  True,  True,  True,  True])

In [74]:
new_array[result_array]

array([ 78,  54,  78,  61, 101,  69,  80, 117,  88,  51, 137,  65,  74,
       101, 130,  52,  94])

In [75]:
last_Array = np.arange(0,30)

In [76]:
last_Array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [77]:
last_Array + last_Array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [78]:
last_Array * last_Array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [79]:
last_Array - last_Array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [81]:
last_Array.max()

29

In [82]:
np.mean(last_Array)

14.5

In [83]:
np.sqrt(last_Array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])